# Generated by Django 5.1 on 2024-09-09 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("map", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mapitem",
            name="description",
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name="mapitem",
            name="name",
            field=models.CharField(max_length=30),
        ),
    ]
