# Generated by Django 5.1 on 2024-09-09 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("map", "0002_alter_mapitem_description_alter_mapitem_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="mapitem",
            name="category",
            field=models.CharField(
                choices=[
                    ("danger", "danger"),
                    ("food bank", "food bank"),
                    ("medical services", "medical services"),
                    ("people", "people"),
                    ("person", "person"),
                    ("pet shelter", "pet shelter"),
                    ("search", "search"),
                    ("shelter", "shelter"),
                    ("warning", "warning"),
                    ("water", "water"),
                ],
                default="danger",
                max_length=16,
            ),
            preserve_default=False,
        ),
    ]
