# Generated by Django 5.1 on 2024-08-29 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "0002_alter_applicationuser_profile_picture"),
    ]

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("publication_date", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=150)),
                ("content", models.TextField(max_length=1500)),
                (
                    "author",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="users.applicationuser",
                    ),
                ),
            ],
        ),
    ]
