# Generated by Django 5.1 on 2024-08-29 01:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0001_initial"),
        ("users", "0002_alter_applicationuser_profile_picture"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="last_updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="post",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="users.applicationuser",
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="publication_date",
            field=models.DateTimeField(),
        ),
    ]
